org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true

# Semantic-release updates these values in the release commit.
VERSION_NAME=1.1.2
VERSION_CODE=100024
