package git.shin.komorei.data.remote

import android.net.Uri
import android.webkit.WebResourceRequest

/**
 * Anti-fingerprint helpers for the app's WebViews.
 *
 * Android WebView appends `X-Requested-With: <applicationId>` to every request.
 * Anti-bot protections (Cloudflare, the localized "Xác Minh An Toàn" challenge,
 * ...) fingerprint that header to detect embedded WebViews and make the JS
 * challenge fail on purpose. Neutralizing it mirrors the reference app
 * (`~/app`'s `CloudflareBypassDialog`): pass [WEBVIEW_ANTI_FINGERPRINT_HEADERS]
 * to `loadUrl(url, headers)` so the autogenerated default is overridden, and
 * strip the header in `shouldInterceptRequest` as well.
 */
val WEBVIEW_ANTI_FINGERPRINT_HEADERS: Map<String, String> =
    mapOf(HEADER_X_REQUESTED_WITH to "")

const val HEADER_X_REQUESTED_WITH = "X-Requested-With"

/**
 * A [WebResourceRequest] whose `X-Requested-With` header has been filtered out.
 * The interface is implemented explicitly (no `by` delegation) so the header
 * filter really takes effect.
 */
class FingerprintFreeWebResourceRequest(
    private val delegate: WebResourceRequest,
) : WebResourceRequest {
    override fun getUrl(): Uri = delegate.url

    override fun isForMainFrame(): Boolean = delegate.isForMainFrame()

    override fun hasGesture(): Boolean = delegate.hasGesture()

    override fun getMethod(): String = delegate.method

    override fun getRequestHeaders(): Map<String, String> =
        delegate.requestHeaders.filterKeys { key ->
            !key.equals(HEADER_X_REQUESTED_WITH, ignoreCase = true)
        }

    override fun isRedirect(): Boolean = delegate.isRedirect()
}

/** Wraps [request] so its `X-Requested-With` header is removed. */
fun stripFingerprintHeaders(request: WebResourceRequest): WebResourceRequest = FingerprintFreeWebResourceRequest(request)
