package git.shin.komorei.ui.components.dialogs

import android.annotation.SuppressLint
import android.webkit.CookieManager
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import git.shin.komorei.R
import git.shin.komorei.data.remote.WEBVIEW_ANTI_FINGERPRINT_HEADERS
import git.shin.komorei.data.remote.stripFingerprintHeaders
import git.shin.komorei.ui.theme.AnimeRed
import git.shin.komorei.ui.theme.BackgroundDark
import git.shin.komorei.ui.theme.SurfaceDark
import git.shin.komorei.ui.theme.TextMuted
import git.shin.komorei.ui.theme.TextPrimary
import git.shin.komorei.ui.tv.tvFocus
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive

/**
 * Visible-browser dialog for the JS-challenge bypass that needs a human
 * (captcha / "xác minh an toàn" pages that the headless WebView cannot clear).
 *
 * Mirrors the reference app's `CloudflareBypassDialog`:
 *  - the page runs in a real JS-enabled WebView, so cookies land in the shared
 *    [CookieManager] that backs [git.shin.komorei.data.remote.WebViewCookieJar];
 *  - requests are defingerprinted: Android's autogenerated
 *    `X-Requested-With: <applicationId>` header is stripped
 *    ([stripFingerprintHeaders] + [WEBVIEW_ANTI_FINGERPRINT_HEADERS] on the
 *    initial load);
 *  - [onNext] fires automatically once the challenge markers vanish from the
 *    DOM, and there is always a manual "Đã xong — Tiếp tục" button as a fallback.
 */
@SuppressLint("SetJavaScriptEnabled")
@Composable
fun ChallengeBypassDialog(
    url: String,
    onNext: () -> Unit,
    onDismiss: () -> Unit,
) {
    var webView by remember { mutableStateOf<WebView?>(null) }
    var canGoBack by remember { mutableStateOf(false) }
    var canGoForward by remember { mutableStateOf(false) }
    var progress by remember { mutableIntStateOf(0) }
    val titleRes = stringResource(R.string.challenge_dialog_title)
    var pageTitle by remember { mutableStateOf(titleRes) }

    DisposableEffect(Unit) {
        onDispose { webView?.destroy() }
    }

    // Auto-detect completion: when the challenge markers disappear from the
    // page, the challenge is solved — hand back to the waiting request without
    // requiring a tap. `result` is the WebView JSON-encoded boolean.
    LaunchedEffect(webView) {
        val view = webView ?: return@LaunchedEffect
        while (isActive) {
            view.evaluateJavascript(CHALLENGE_CLEARED_JS) { result ->
                if (result == "true") onNext()
            }
            delay(1_500)
        }
    }

    Dialog(
        onDismissRequest = onDismiss,
        properties =
            DialogProperties(
                usePlatformDefaultWidth = false,
                dismissOnBackPress = true,
                dismissOnClickOutside = false,
            ),
    ) {
        Surface(modifier = Modifier.fillMaxSize(), color = BackgroundDark) {
            Column(modifier = Modifier.fillMaxSize().statusBarsPadding().navigationBarsPadding()) {
                Row(
                    modifier = Modifier.fillMaxWidth().padding(horizontal = 6.dp, vertical = 10.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(2.dp),
                ) {
                    IconButton(
                        onClick = onDismiss,
                        modifier =
                            Modifier
                                // TV focus highlight (no-op on phones).
                                .tvFocus(shape = CircleShape, scale = 1.15f)
                                .testTag("challenge_close"),
                    ) {
                        Icon(
                            imageVector = Icons.Filled.Close,
                            contentDescription = stringResource(R.string.challenge_dialog_cd_close),
                            tint = TextPrimary,
                            modifier = Modifier.size(20.dp),
                        )
                    }
                    Column(modifier = Modifier.weight(1f)) {
                        Text(
                            text = pageTitle,
                            color = TextPrimary,
                            fontSize = 15.sp,
                            fontWeight = FontWeight.Bold,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                        )
                        Text(
                            text = webView?.url ?: url,
                            color = TextMuted,
                            fontSize = 11.sp,
                            lineHeight = 14.sp,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                        )
                    }
                    IconButton(
                        onClick = { if (progress < 100) webView?.stopLoading() else webView?.reload() },
                        // TV focus highlight (no-op on phones).
                        modifier = Modifier.tvFocus(shape = CircleShape, scale = 1.15f),
                    ) {
                        Icon(
                            imageVector = if (progress < 100) Icons.Filled.Close else Icons.Filled.Refresh,
                            contentDescription = stringResource(R.string.source_browser_cd_reload),
                            tint = TextPrimary,
                            modifier = Modifier.size(20.dp),
                        )
                    }
                }
                if (progress < 100) {
                    LinearProgressIndicator(
                        progress = { progress / 100f },
                        modifier = Modifier.fillMaxWidth().height(2.dp),
                        color = AnimeRed,
                        trackColor = Color.Transparent,
                    )
                }
                Text(
                    text = stringResource(R.string.challenge_dialog_hint),
                    color = TextMuted,
                    fontSize = 12.sp,
                    lineHeight = 16.sp,
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
                )
                AndroidView(
                    factory = { ctx ->
                        WebView(ctx).apply {
                            layoutParams =
                                android.view.ViewGroup.LayoutParams(
                                    android.view.ViewGroup.LayoutParams.MATCH_PARENT,
                                    android.view.ViewGroup.LayoutParams.MATCH_PARENT,
                                )
                            settings.javaScriptEnabled = true
                            settings.domStorageEnabled = true
                            settings.mixedContentMode = WebSettings.MIXED_CONTENT_ALWAYS_ALLOW
                            CookieManager.getInstance().setAcceptCookie(true)
                            CookieManager.getInstance().setAcceptThirdPartyCookies(this, true)
                            webViewClient =
                                object : WebViewClient() {
                                    override fun onPageFinished(
                                        view: WebView,
                                        url: String?,
                                    ) {
                                        super.onPageFinished(view, url)
                                        canGoBack = view.canGoBack()
                                        canGoForward = view.canGoForward()
                                    }

                                    // "Chặn request": hide the Android WebView
                                    // fingerprint header like the reference app.
                                    override fun shouldInterceptRequest(
                                        view: WebView,
                                        request: WebResourceRequest,
                                    ): WebResourceResponse? = super.shouldInterceptRequest(view, stripFingerprintHeaders(request))

                                    override fun shouldOverrideUrlLoading(
                                        view: WebView,
                                        request: WebResourceRequest,
                                    ): Boolean = false
                                }
                            webChromeClient =
                                object : WebChromeClient() {
                                    override fun onProgressChanged(
                                        view: WebView?,
                                        newProgress: Int,
                                    ) {
                                        progress = newProgress
                                    }

                                    override fun onReceivedTitle(
                                        view: WebView?,
                                        title: String?,
                                    ) {
                                        if (!title.isNullOrBlank()) pageTitle = title
                                    }
                                }
                            loadUrl(url, WEBVIEW_ANTI_FINGERPRINT_HEADERS)
                            webView = this
                        }
                    },
                    modifier = Modifier.weight(1f).fillMaxWidth(),
                    update = { webView = it },
                )
                Row(
                    modifier =
                        Modifier
                            .fillMaxWidth()
                            .background(SurfaceDark)
                            .padding(horizontal = 8.dp, vertical = 4.dp),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    IconButton(
                        onClick = onDismiss,
                        modifier =
                            Modifier
                                // TV focus highlight (no-op on phones).
                                .tvFocus(shape = CircleShape, scale = 1.15f)
                                .testTag("challenge_dismiss"),
                    ) {
                        Icon(
                            imageVector = Icons.Filled.Close,
                            contentDescription = stringResource(R.string.challenge_dialog_cd_close),
                            tint = TextPrimary,
                            modifier = Modifier.size(20.dp),
                        )
                    }
                    IconButton(
                        onClick = { webView?.goBack() },
                        enabled = canGoBack,
                        modifier =
                            Modifier
                                // TV focus highlight (no-op on phones).
                                .tvFocus(shape = CircleShape, scale = 1.15f)
                                .testTag("challenge_back"),
                    ) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = stringResource(R.string.source_browser_cd_back),
                            tint = TextPrimary,
                            modifier = Modifier.size(20.dp),
                        )
                    }
                    IconButton(
                        onClick = { webView?.goForward() },
                        enabled = canGoForward,
                        // TV focus highlight (no-op on phones).
                        modifier = Modifier.tvFocus(shape = CircleShape, scale = 1.15f),
                    ) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowForward,
                            contentDescription = stringResource(R.string.source_browser_cd_forward),
                            tint = TextPrimary,
                            modifier = Modifier.size(20.dp),
                        )
                    }
                    Spacer(modifier = Modifier.weight(1f))
                    TextButton(
                        onClick = onNext,
                        modifier =
                            Modifier
                                // TV focus highlight (no-op on phones).
                                .tvFocus(shape = RoundedCornerShape(8.dp), scale = 1.05f)
                                .testTag("challenge_continue"),
                    ) {
                        Text(
                            text = stringResource(R.string.challenge_dialog_continue),
                            color = AnimeRed,
                            fontWeight = FontWeight.Bold,
                        )
                    }
                }
            }
        }
    }
}

/** Returns JS `true` once the challenge markers are gone from the DOM. */
private const val CHALLENGE_CLEARED_JS =
    "(function(){" +
        "var b=document.body;if(!b)return false;" +
        "var t=((b.innerText||\"\")+(document.title||\"\")).toLowerCase();" +
        "if(t.indexOf(\"just a moment\")!==-1)return false;" +
        "if(t.indexOf(\"cf-challenge\")!==-1)return false;" +
        "if(t.indexOf(\"cf-browser-verification\")!==-1)return false;" +
        "if(t.indexOf(\"ray-id\")!==-1)return false;" +
        "if(t.indexOf(\"xác minh an toàn\")!==-1)return false;" +
        "if(t.indexOf(\"xác minh khu vực\")!==-1)return false;" +
        "if(document.querySelector(\".captcha-placeholder\"))return false;" +
        "return true;" +
        "})()"
